/** Auto-generated by vue-nnn-router — do not edit */
import type { NnnScrollMap, NnnSmoothScrollMap } from "vue-nnn-router";

export const NNN_SCROLL: NnnScrollMap = {
  "src/pages/settings/notifications.vue": {"top":80,"smooth":true},
};

export const NNN_SMOOTH_SCROLL: NnnSmoothScrollMap = {
  "src/pages/about/index.vue": {"enabled":false},
  "src/pages/smooth-scroll.vue": {"enabled":true,"disableOnMobile":true},
};
