/** Auto-generated by vue-nnn-router — do not edit */
export const ROUTER_NAME = {
  about: "about",
  adminDashboard: "admin-dashboard",
  adminLayout: "admin-layout",
  adminRedirect: "admin-redirect",
  home: "home",
  settingsLayout: "settings-layout",
  settingsNotifications: "settings-notifications",
  settingsProfile: "settings-profile",
  settingsRedirect: "settings-redirect",
  users: "users",
  usersAdd: "users-add",
  usersId: "users-id",
  usersLayout: "users-layout",

} as const;

export type RouterName = (typeof ROUTER_NAME)[keyof typeof ROUTER_NAME];
