import type { RouteRecordRaw } from "vue-router";

/** Map camelCase key → Vue Router `route.name`. */
export type RouterNameMap = Record<string, string>;

export type CollectRouteNamesOptions = {
  silent?: boolean;
  logger?: (...args: unknown[]) => void;
};

/** `users-add` → `usersAdd`; `home` → `home`. */
export function routeNameToCamelKey(routeName: string): string {
  const parts = routeName.split("-").filter(Boolean);
  if (parts.length === 0) return "home";
  const [first, ...rest] = parts;
  return (
    first! +
    rest.map((p) => (p.length ? p.charAt(0).toUpperCase() + p.slice(1) : "")).join("")
  );
}

function walkRouteNames(
  routes: readonly RouteRecordRaw[],
  into: RouterNameMap,
  opts: CollectRouteNamesOptions,
): void {
  for (const r of routes) {
    if (typeof r.name === "string" && r.name.length > 0) {
      const key = routeNameToCamelKey(r.name);
      const prev = into[key];
      if (prev !== undefined && prev !== r.name && opts.silent !== true) {
        (opts.logger ?? console.warn)(
          `[vue-nnn-router] Duplicate ROUTER_NAME key "${key}" for names "${prev}" and "${r.name}".`,
        );
      } else if (prev === undefined) {
        into[key] = r.name;
      }
    }
    if (r.children?.length) walkRouteNames(r.children, into, opts);
  }
}

/** Build `{ usersAdd: "users-add", … }` from generated routes. */
export function collectRouteNames(
  routes: readonly RouteRecordRaw[],
  options: CollectRouteNamesOptions = {},
): RouterNameMap {
  const out: RouterNameMap = {};
  walkRouteNames(routes, out, options);
  return out;
}

/** Emit source for `router-name.ts` (export `ROUTER_NAME`). */
export function formatRouterNameModule(names: RouterNameMap): string {
  const entries = Object.entries(names).sort(([a], [b]) => a.localeCompare(b));
  const body =
    entries.length === 0
      ? ""
      : entries.map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join("\n") + "\n";
  return [
    "/** Auto-generated by vue-nnn-router — do not edit */",
    "export const ROUTER_NAME = {",
    body,
    "} as const;",
    "",
    "export type RouterName = (typeof ROUTER_NAME)[keyof typeof ROUTER_NAME];",
    "",
  ].join("\n");
}
