import type { NnnScrollMap, NnnScrollMeta } from "./scrollMeta";
import { normalizeNnnScroll } from "./scrollMeta";
import type { NnnSmoothScrollMap } from "./smoothScrollMeta";

/** Reject arguments that could execute code or read the environment. */
const UNSAFE = /\b(require|import|process|globalThis|eval|Function|fetch|window|document|await|new)\b|=>|`|;/;

export function findCallArg(code: string, name: string): string | null {
  const escapedName = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const call = new RegExp(`${escapedName}\\s*\\(`, "g");
  const m = call.exec(code);
  if (!m) return null;

  let i = m.index + m[0].length;
  let depth = 1;
  let quote: string | null = null;
  const start = i;

  for (; i < code.length; i++) {
    const ch = code[i]!;
    if (quote) {
      if (ch === "\\") {
        i++;
        continue;
      }
      if (ch === quote) quote = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      quote = ch;
      continue;
    }
    if (ch === "(" || ch === "[" || ch === "{") depth++;
    else if (ch === ")" || ch === "]" || ch === "}") {
      depth--;
      if (depth === 0) return code.slice(start, i).trim();
    }
  }
  return null;
}

/**
 * Find the argument passed to the first `defineNnnScroll(...)` call in `code`.
 * Returns the raw source of the argument, or `null` when there is no call.
 */
export function findNnnScrollArg(code: string): string | null {
  return findCallArg(code, "defineNnnScroll");
}

export function evalLiteralConfigArg<T>(
  arg: string | null,
  normalize: (value: Record<string, unknown> | boolean) => T,
): T | null {
  if (arg == null) return null;
  const src = arg.trim();
  if (src === "") return null;
  if (src === "true" || src === "false") {
    return normalize(src === "true");
  }
  if (!src.startsWith("{") || UNSAFE.test(src)) return null;
  try {
    // Build-time only, over the user's own source, guarded by UNSAFE above.
    const value = new Function(`"use strict";return (${src});`)();
    if (value == null || typeof value !== "object" || Array.isArray(value)) {
      return null;
    }
    return normalize(value as Record<string, unknown>);
  } catch {
    return null;
  }
}

/**
 * Statically evaluate a `defineNnnScroll(...)` argument (object literal or
 * boolean) into an `NnnScrollMeta`. Returns `null` when the argument is empty,
 * dynamic, or otherwise unsafe to evaluate.
 */
export function evalNnnScrollArg(arg: string | null): NnnScrollMeta | null {
  return evalLiteralConfigArg(
    arg,
    normalizeNnnScroll as (
      value: Record<string, unknown> | boolean,
    ) => NnnScrollMeta,
  );
}

/** Extract the per-page scroll config declared in a single page file. */
export function extractNnnScroll(code: string): NnnScrollMeta | null {
  return evalNnnScrollArg(findNnnScrollArg(code));
}

function formatMapEntries(
  map: NnnScrollMap | NnnSmoothScrollMap,
): string {
  const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));
  return entries.length === 0
    ? ""
    : entries
        .map(
          ([key, value]) =>
            `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`,
        )
        .join("\n") + "\n";
}

/** Emit the generated module containing navigation and continuous scroll maps. */
export function formatScrollMapModule(
  map: NnnScrollMap,
  smoothMap: NnnSmoothScrollMap = {},
): string {
  return [
    "/** Auto-generated by vue-nnn-router — do not edit */",
    'import type { NnnScrollMap, NnnSmoothScrollMap } from "vue-nnn-router";',
    "",
    `export const NNN_SCROLL: NnnScrollMap = {\n${formatMapEntries(map)}};`,
    "",
    `export const NNN_SMOOTH_SCROLL: NnnSmoothScrollMap = {\n${formatMapEntries(smoothMap)}};`,
    "",
  ].join("\n");
}
