import type { NnnScrollMap, NnnScrollMeta } from "./scrollMeta";
import { normalizeNnnScroll } from "./scrollMeta";

/** Reject arguments that could execute code or read the environment. */
const UNSAFE = /\b(require|import|process|globalThis|eval|Function|fetch|window|document|await|new)\b|=>|`|;/;

/**
 * Find the argument passed to the first `defineNnnScroll(...)` call in `code`.
 * Returns the raw source of the argument, or `null` when there is no call.
 */
export function findNnnScrollArg(code: string): string | null {
  const call = /defineNnnScroll\s*\(/g;
  const m = call.exec(code);
  if (!m) return null;

  let i = m.index + m[0].length;
  let depth = 1;
  let quote: string | null = null;
  const start = i;

  for (; i < code.length; i++) {
    const ch = code[i]!;
    if (quote) {
      if (ch === "\\") {
        i++;
        continue;
      }
      if (ch === quote) quote = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      quote = ch;
      continue;
    }
    if (ch === "(" || ch === "[" || ch === "{") depth++;
    else if (ch === ")" || ch === "]" || ch === "}") {
      depth--;
      if (depth === 0) return code.slice(start, i).trim();
    }
  }
  return null;
}

/**
 * Statically evaluate a `defineNnnScroll(...)` argument (object literal or
 * boolean) into an `NnnScrollMeta`. Returns `null` when the argument is empty,
 * dynamic, or otherwise unsafe to evaluate.
 */
export function evalNnnScrollArg(arg: string | null): NnnScrollMeta | null {
  if (arg == null) return null;
  const src = arg.trim();
  if (src === "") return null;
  if (src === "true" || src === "false") {
    return normalizeNnnScroll(src === "true");
  }
  if (!src.startsWith("{") || UNSAFE.test(src)) return null;
  try {
    // Build-time only, over the user's own source, guarded by UNSAFE above.
    const value = new Function(`"use strict";return (${src});`)();
    if (value == null || typeof value !== "object") return null;
    return normalizeNnnScroll(value as NnnScrollMeta);
  } catch {
    return null;
  }
}

/** Extract the per-page scroll config declared in a single page file. */
export function extractNnnScroll(code: string): NnnScrollMeta | null {
  return evalNnnScrollArg(findNnnScrollArg(code));
}

/** Emit source for the generated scroll-map module (`export NNN_SCROLL`). */
export function formatScrollMapModule(map: NnnScrollMap): string {
  const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));
  const body =
    entries.length === 0
      ? ""
      : entries
          .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
          .join("\n") + "\n";
  return [
    "/** Auto-generated by vue-nnn-router — do not edit */",
    'import type { NnnScrollMap } from "vue-nnn-router";',
    "",
    "export const NNN_SCROLL: NnnScrollMap = {",
    body,
    "};",
    "",
  ].join("\n");
}
