import Lenis, { type LenisOptions } from "lenis";
import type { RouteLocationNormalizedLoaded, Router } from "vue-router";
import { simplifyGlobKey } from "./globUtils";
import type {
  NnnSmoothScrollMap,
  NnnSmoothScrollMeta,
} from "./smoothScrollMeta";

export interface NnnSmoothScrollOptions {
  /** Default state for pages without an override. Default: true. */
  enabled?: boolean;
  /** Use native scrolling on mobile. Default: false. */
  disableOnMobile?: boolean;
  /** Maximum viewport width considered mobile, in px. Default: 767. */
  mobileBreakpoint?: number;
  /** Per-page overrides generated by `vueNnnRouterScrollPlugin`. */
  scrollMap?: NnnSmoothScrollMap;
  /** Options forwarded to Lenis. `autoRaf` defaults to true. */
  lenisOptions?: LenisOptions;
}

export interface NnnSmoothScrollHandle {
  /** The active Lenis instance, or `undefined` while native scrolling is used. */
  readonly instance: Lenis | undefined;
  /** Whether continuous smooth scrolling is currently active. */
  readonly active: boolean;
  /** Re-evaluate the current route and mobile breakpoint. */
  refresh(): void;
  /** Remove router/media listeners and destroy the active Lenis instance. */
  destroy(): void;
}

function pageMeta(
  route: RouteLocationNormalizedLoaded,
  scrollMap: NnnSmoothScrollMap | undefined,
): NnnSmoothScrollMeta | undefined {
  const inline = route.meta?.nnnSmoothScroll as
    | NnnSmoothScrollMeta
    | undefined;
  if (inline) return inline;
  if (!scrollMap) return undefined;

  const file = route.meta?.nnnFile;
  if (typeof file !== "string") return undefined;
  return scrollMap[simplifyGlobKey(file)];
}

function addMediaListener(
  media: MediaQueryList,
  listener: () => void,
): () => void {
  if (typeof media.addEventListener === "function") {
    media.addEventListener("change", listener);
    return () => media.removeEventListener("change", listener);
  }

  media.addListener(listener);
  return () => media.removeListener(listener);
}

/**
 * Attach Lenis continuous smooth scrolling to a Vue Router instance.
 * Lenis is created only while the current page is enabled; disabled pages and
 * mobile opt-outs use native scrolling with no Lenis listeners left behind.
 */
export function createNnnSmoothScroll(
  router: Router,
  options: NnnSmoothScrollOptions = {},
): NnnSmoothScrollHandle {
  const {
    enabled = true,
    disableOnMobile = false,
    mobileBreakpoint = 767,
    scrollMap,
    lenisOptions = {},
  } = options;

  let instance: Lenis | undefined;
  let destroyed = false;
  const media =
    typeof window !== "undefined" && typeof window.matchMedia === "function"
      ? window.matchMedia(`(max-width: ${mobileBreakpoint}px)`)
      : undefined;

  const isMobile = () => {
    if (typeof window === "undefined") return false;
    return media?.matches ?? window.innerWidth <= mobileBreakpoint;
  };

  const destroyInstance = () => {
    instance?.destroy();
    instance = undefined;
  };

  const refresh = () => {
    if (destroyed || typeof window === "undefined") return;

    const page = pageMeta(router.currentRoute.value, scrollMap);
    const pageEnabled = page?.enabled ?? enabled;
    const mobileDisabled = page?.disableOnMobile ?? disableOnMobile;
    const shouldRun = pageEnabled && !(mobileDisabled && isMobile());

    if (shouldRun && !instance) {
      instance = new Lenis({ autoRaf: true, ...lenisOptions });
    } else if (!shouldRun && instance) {
      destroyInstance();
    }
  };

  const removeRouterHook = router.afterEach(refresh);
  const removeMediaListener = media
    ? addMediaListener(media, refresh)
    : () => undefined;

  if (typeof window !== "undefined" && typeof router.isReady === "function") {
    void router.isReady().then(refresh, () => undefined);
  } else {
    refresh();
  }

  return {
    get instance() {
      return instance;
    },
    get active() {
      return instance !== undefined;
    },
    refresh,
    destroy() {
      if (destroyed) return;
      destroyed = true;
      removeRouterHook();
      removeMediaListener();
      destroyInstance();
    },
  };
}
